const gameData = {
  cellSize: 50.0,
  cameraWidth: 1000,
  cameraHeight: 500,
  floorY: 400,
  worldHeight: 10,
  cameraChaseX: 100.0,
  gravityForce: 0.5,
  player: {
    headSize: 25,
    bodyHeight: 50,
    bodyWidth: 25,
    startX: 100.0,
    startY: 350.0,
    speed: 6.0,
    jumpForce: 10.0,
  },
  types: {
    player: "player",
    floor: "floor",
    start: "start",
    spikeUp: "spikeUp",
    end: "end",
    space: "space",
  },
  states: {
    notStarted: "not started",
    playing: "playing",
    won: "won",
    died: "died",
    editing: "editing",
  },
  commands: {
    toggleEditing: 69,
    editingCameraMoveLeft: 65,
    editingCameraMoveRight: 83,
  },
  level: [],
  cloneAmountWhileEditing: 5,
};
