const gameData = {
  cellSize: 50.0,
  cameraWidth: 1000,
  cameraHeight: 500,
  floorY: 400,
  worldHeight: 10,
  cameraChaseX: 100.0,
  gravityForce: 1.0,
  player: {
    headSize: 25,
    bodyHeight: 50,
    bodyWidth: 25,
    startX: 100.0,
    startY: 350.0,
    speed: 4.0,
    jumpForce: 5.0,
  },
  types: {
    player: "player",
    floor: "floor",
    start: "start",
    spikeUp: "spikeUp",
    end: "end",
  },
  states: {
    notStarted: "not started",
    playing: "playing",
    won: "won",
    died: "died",
  },
  level: [
    "floor",
    "floor",
    "start",
    "floor",
    "floor",
    "space",
    "floor",
    "spikeUp",
    "space",
    "space",
    "space",
    "floor",
    "space",
    "floor",
    "space",
    "floor",
    "space",
    "floor",
    "floor",
    "floor",
    "space",
    "floor",
    "floor",
    "floor",
    "space",
    "floor",
    "floor",
    "floor",
    "space",
    "floor",
    "floor",
    "floor",
    "space",
    "floor",
    "floor",
    "floor",
    "floor",
    "end",
    "floor",
    "floor",
    "floor",
  ],
};
